apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xkx0cmvlw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xkx0cmvlw-nodejs 
  name: xkx0cmvlw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xkx0cmvlw-nodejs 
